## Accessing specific elements, rows, columns-1:
## Figure out the dimensionality

In [15]:
# Define an array
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
2
(2, 7)


In [16]:
# Get a specific element [r, c], in which r: row and c: column.
print(a[1, 5])
# Get a specific row 
print(a[0, :])
# Get a specific column
print(a[:, 0])

13
[1 2 3 4 5 6 7]
[1 8]


In [17]:
# Now, let's try dealing with arrays with even higher dimensions!
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b.ndim)
print(b.shape)

# Let's see the output for:
print(b[0,1,1])

3
(2, 2, 2)
4


In [18]:
print("First array")
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# replacement-1: Now I want to change [3, 4] by [10,10]
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,:] = [10,10]
print("Array variant-1")
print(b)

# repalcement-2: change [2, 4] by 10 10
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,:,1] = [10,10]
print("Array variant-2")
print(b)

First array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array variant-1
[[[ 1  2]
  [10 10]]

 [[ 5  6]
  [ 7  8]]]
Array variant-2
[[[ 1 10]
  [ 3 10]]

 [[ 5  6]
  [ 7  8]]]


### Individual assignment: define an array b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
### Q-1: replace 5 7 by 10 10 

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# Your code goes here:
b[1,:,0] = [10,10]
print("New array-1")
print(b)

### Q-2: replace 1 3 by 10 10 

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# Your code goes here:
b[0,:,0] = [10,10]
print("New array-2")
print(b)

## Accessing specific elements, rows, columns-2:
## Use logical operation
### Example: find all the odd number in an array.

In [2]:
import numpy as np
# The entire operation can be expressed using one line of code:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a[ a%2 == 1 ])

# Using array:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
t = (a % 2 == 1)
print(t)
print("The sliced numpy array is:", a[t])

# Question: How to achieve the same goal by using List comprehension?

[1 3 5 7 9]
[False  True False  True False  True False  True False  True False]
The sliced numpy array is: [1 3 5 7 9]


### Individual assignment: Extract the numbers that are divisible by 3 from the following numpy array arr = np.array([0, 2, 3, 4, 5, 6, 8, 9, 13, 19])

In [3]:
arr = np.array([0, 2, 3, 4, 5, 6, 8, 9, 13, 20])
# Your code goes here:
print(a[ a%3 == 0 ])

[0 3 6 9]


### Individual assignment: following is the given numpy array return array of odd rows and even columns A = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
### [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
### ``Q1``: Printing array of the third row?
### [27 30 33 36]
### ``Q2``: Printing array of the last column?
### [12 24 36 48 60]
### ``Q3``: Printing the odd numbers of the array?
### [ 3  9 15 21 27 33 39 45 51 57]


In [7]:
import numpy as np
A = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
# Your code for Q1
print(A[2])
print(A[2, :])
# Your code for Q2
print(A[:,-1])
print(A[:,-1])
# Your code for Q3
print(A[A%2 == 1])

[27 30 33 36]
[27 30 33 36]
[12 24 36 48 60]
[12 24 36 48 60]
[ 3  9 15 21 27 33 39 45 51 57]


## Numpy
- ## Array initiation
- ## Array mathematics: statistics, linear algebra, and Arithmetic 
- ## Array organization


### Array Initiation

In [8]:
# All 0s matrix
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# All 1s matrix
print(np.ones((4,2,2)))

In [ ]:
# Any other number
np.full((4,2,2),99)

In [ ]:
# Any other number (full_like)
a = np.array([1,2,3,4,5]) 
np.full_like(a, 4)

In [ ]:
# Random floating point numbers
np.random.rand(4,2)

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

In [ ]:
# Coping array: need to be very careful!
# Case-1
a = np.array([1,2,3])
b = a # let's see what will happen!
b[0] = 100
print("With b = a", a)

# Case-2
a = np.array([1,2,3])
b = a.copy() 
b[0] = 100
print(a)

### Arithmetic

In [ ]:
a = np.array([1,2,3,4])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
print(a + b)
print(a*b)

In [ ]:
np.cos(a)

### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
# Find the inverse matrix
d = np.array([[ 4,  4, -1], [-2, -3,  5], [ 7, -2,  7]])
d_inv = np.linalg.inv(d)
unit = np.matmul(d,d_inv)
print(unit)
np.around(unit)

In [11]:
# Perform transpose
d = np.array([[ 4,  4, -1], [-2, -3,  5], [ 7, -2,  7]])
print(d)
d_tp = np.transpose(d)
print(d_tp)

[[ 4  4 -1]
 [-2 -3  5]
 [ 7 -2  7]]
[[ 4 -2  7]
 [ 4 -3 -2]
 [-1  5  7]]


### Statistics

### Q: What will be the output?
### stats = np.array([[1,2,3],[4,5,6]])
### print(np.max(stats, axis=0))

In [10]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
#print(np.min(stats))
print(np.max(stats, axis=0))
print(np.max(stats, axis=1))
print(np.sum(stats, axis=0))
print(np.mean(stats, axis=0))

[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 6]
[5 7 9]
[2.5 3.5 4.5]


### individual assignment: Vectorize your equation.
### From Newtonian Equation of Motion, we learned that F = Ma. 

### In this equation, ``M`` refers to mass and ``a`` refers to acceleration. M=[2,2,2,4,4,4,7,7]; a=[1,2,3,4,5,6,7,8]; 

### Compute the outcome of the force of the system, which is defined as F = ΣiMi*ai

In [9]:
# Using For loop:

M = [2,2,2,4,4,4,7,7]

a = [1,2,3,4,5,6,7,8]

if len(M) == len(a):
# Your code goes here:
    
else:
    print("Mismatch in the length of M and a")

IndentationError: expected an indented block (<ipython-input-9-7bb7cd84ed82>, line 10)

In [37]:
# Using Numpy loop:
import numpy as np

M = np.array([2,2,2,4,4,4,7,7])

a = np.array([1,2,3,4,5,6,7,8])

# Your code goes here:


177


### Timing the code

In [ ]:
import time

# Using For loop:
t0 = time.time()

M = [2,2,2,4,4,4,7,7]
a = [1,2,3,4,5,6,7,8]
if len(M) == len(a):
    F = [M[i]*a[i] for i in range(len(M))]
    print(sum(F))
else:
    print("Mismatch in the length of M and a")

t1 = time.time()
print("Using for loop", t1-t0)

# Using For loop:
t0 = time.time()

M = np.array([2,2,2,4,4,4,7,7])
a = np.array([1,2,3,4,5,6,7,8])
print(np.sum(M*a, axis = 0))

t1 = time.time()
print("Using numpy", t1-t0)

### Reorganizing arrays
- ### Flatten
- ### Reshape

In [21]:
# flatten
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.flatten()
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
# Reshape
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

## Q1: Replace all odd numbers in arr with -1 without changing arr
## arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
## output array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]

In [23]:
# Q1: replacing odd number by -1
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Your code goes here


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Q2: Here is a numpy array:
## A= [[2, 7, 8, 2, 0, 7],
##       [2, 9, 0, 3, 4, 6],
##       [1, 9, 9, 8, 8, 4],
##       [2, 4, 1, 5, 3, 2]]
## Compute the mean value for each column

In [ ]:
# Q2: Compute the average for each column
A = np.array([[2, 7, 8, 2, 0, 7],
       [2, 9, 0, 3, 4, 6],
       [1, 9, 9, 8, 8, 4],
       [2, 4, 1, 5, 3, 2]])
# Your code goes here:


## Q3: Here is a numpy array:
## A= [[2, 7, 8, 2, 0, 7],
##       [2, 9, 0, 3, 4, 6],
##       [1, 9, 9, 8, 8, 4],
##       [2, 4, 1, 5, 3, 2]]
## Print the maximum value for each row

In [ ]:
# Q3: Compute the average for each row
A = np.array([[2, 7, 8, 2, 0, 7],
       [2, 9, 0, 3, 4, 6],
       [1, 9, 9, 8, 8, 4],
       [2, 4, 1, 5, 3, 2]])
# Your code goes here:
