# Assignment 11

In this assignment, ***LOOPS ARE NOT ALLOWED***</font> unless specified in the question.

## Part 1: Numpy Arrays (50 pts)

In [1]:
import numpy as np

#### 1. Using the appropriate functions for lists, make a list `L` of all integers from 0 - 19 (inclusive). （5 pts)

In [2]:
L = [i for i in range(20)]
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


#### 2. Use a numpy function to convert `L` into a numpy array. (5 pts)

In [3]:
L = np.array(L)
print(L)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 3. Using numpy functions, compute the mean and standard deviation of `L`. (10 pts)

In [4]:
L_mean = np.mean(L)
L_std = np.std(L)
print(L_mean)
print(L_std)

9.5
5.766281297335398


#### 4. Using a numpy function, change `L` into a 5 by 4 matrix (5 row, 4 columns). Replace the last column by a vector of 0. (10pts)

In [5]:
L = L.reshape(5,4)
print(L)
L[:,3]=0
print(L)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]
 [16 17 18  0]]


#### 5. Using a numpy function (not a loop) compute the mean of the elements in each column of `L`. Also use a numpy function to compute the standard deviation of the elements in each row. (10 pts)
#### Hint: Google or Take a look at numpy documentation.

In [6]:
L_col_mean = np.mean(L,axis=0)
L_row_std = np.std(L,axis=1)
print(L_col_mean)
print(L_row_std)

[ 8.  9. 10.  0.]
[0.8291562  2.27760839 3.96074488 5.67340286 7.39509973]


#### 6. Let's use numpy's random number generator. Seed it below with the number "2". (Note -- for the sake of reproducability, it's always a good idea to seed a random number generator.) After generating the seed, using a numpy function, create two arrays each of 10 random integers between 1 and 3 (inclusive). Name these arrays `A` and `B`. (10 pts)

In [7]:
np.random.seed(2)
A = np.random.randint(1,4,10)
B = np.random.randint(1,4,10)
print(A)
print(B)

[1 2 1 3 3 1 3 2 2 3]
[1 1 1 2 3 1 3 3 3 2]


## Part 2: Matrix Multiplication (30 pts)
A common programming problem involves writing a function to perform a matrix multiplication. Please review the procedure for multiplying two matrices if you have forgotten. In this section you'll perform matrix multiplications using the following matrices:

In [8]:
M=np.array([[3,5,3],[2,4,3],[4,2,2]])
N=np.array([[1,2,2],[1,1,2],[4,5,1]])
L=np.array([[1,5,2,4],[3,5,3,5],[1,1,2,4]])
print(M)
print(N)
print(L)

[[3 5 3]
 [2 4 3]
 [4 2 2]]
[[1 2 2]
 [1 1 2]
 [4 5 1]]
[[1 5 2 4]
 [3 5 3 5]
 [1 1 2 4]]


**1. Write a function called `matrix_multiply` that takes in two matrices and returns their matrix product. Test that the function works for `M` x `N` and `N` x `L`. For `L` x `M`, raise an appropriate error message to indicate the issue. For this part, do not use any built-in numpy functions designed for matrix multiplication. (20pts)** <br>
**(Note: don't worry if your function changes the integers to floats. You can fix this if you like!)** <br> 
<b>Example:</b> <br>
    Input: [[3,5,3],[2,4,3],[4,2,2]], [[1,2,2],[1,1,2],[4,5,1]] <br>
    Output: [[20 26 19][18 23 15][14 20 14]]

In [9]:
def matrix_multiply(m1, m2):
    m1_row, m1_col = m1.shape
    m2_row, m2_col = m2.shape
    if m1_col != m2_row:
        raise ValueError("Error! These two matrices cannot be multiplied")
    else:
        matrix_products = []
        ans = [[0 for row in range(m2_col)] for col in range(m1_row)]
        for i in range(m1_row):
            for j in range(m2_col):
                for k in range(m1_col):
                    ans[i][j] += m1[i][k] * m2[k][j]
        return ans
        

In [10]:
print(matrix_multiply(M, N))
print(matrix_multiply(N, L))
print(matrix_multiply(L, N))

[[20, 26, 19], [18, 23, 15], [14, 20, 14]]
[[9, 17, 12, 22], [6, 12, 9, 17], [20, 46, 25, 45]]


ValueError: Error! These two matrices cannot be multiplied

#### 2. What function(s) already exist in numpy for performing matrix multiplication? Using one or more of these functions, check that your function is performing correctly. What type of error is raised when you try to multiply `L` by `N`? Describe the error briefly.  (10 pts)

In [11]:
print(np.dot(M,N))
print(np.dot(N,L))
print(np.dot(L,N))

[[20 26 19]
 [18 23 15]
 [14 20 14]]
[[ 9 17 12 22]
 [ 6 12  9 17]
 [20 46 25 45]]


ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

`np.dot`function can perform matrix multiplication. In the value error description: shapes (3,4) and (3,3) not aligned. So, this error due to the dimension of L is not equal to the dimension of N, which means these 2 matrix cannot be multplied.

## Part 3: Itertools (20 pts)

In [12]:
import itertools

Before you dive into this section, you are encouraged to go through a <a href="https://www.youtube.com/watch?v=0owC1x2o4U8">video tutorial</a> and the <a href="https://docs.python.org/3/library/itertools.html">documentation</a> of `itertools`.  

**1. Assume you have some dollar bills in your wallet. You have three 20 dollar bills, five 10 dollar bills, six 5 dollar bills, and five 1 dollar bills. Use a list to save all the paper money you have:**

In [13]:
wallet = [1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 20, 20, 20]

**(a) Suppose you are picking five bills from your wallet. Use `itertools.combination` methods to list all the combinations of possible bill combinations and get the number of combinations. Print the result. (5 pts)** 

In [14]:
counts=0
for i in itertools.combinations(wallet,5):
    counts += 1
print ("The number of combinations is", counts)

for j in itertools.combinations(wallet,5):
    print (j)
    

The number of combinations is 11628
(1, 1, 1, 1, 1)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 20)
(1, 1, 1, 1, 20)
(1, 1, 1, 1, 20)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 10)
(1, 1, 1, 1, 20)
(1, 1, 1, 1, 20)
(1, 1, 1, 1, 20)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 20)
(1, 1, 1, 5, 20)
(1, 1, 1, 5, 20)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 10)
(1, 1, 1, 5, 20)
(1, 1, 1, 5, 20)
(1, 1, 1, 5, 20)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 5)
(1, 1, 1, 5, 10)
(1,

(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 20, 20)
(1, 5, 5, 20, 20)
(1, 5, 5, 20, 20)
(1, 5, 5, 5, 5)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 20)
(1, 5, 5, 5, 20)
(1, 5, 5, 5, 20)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 10)
(1, 5, 5, 5, 20)
(1, 5, 5, 5, 20)
(1, 5, 5, 5, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 

(1, 5, 5, 10, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 10)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 10, 20)
(1, 5, 5, 20, 20)
(1, 5, 5, 20, 20)
(1, 5, 5, 20, 20)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 20, 20)
(1, 5, 10, 20, 20)
(1, 5, 10, 20, 20)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 10)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 10, 20)
(1, 5, 10, 20, 20)
(1, 5, 10, 20, 20)
(1, 5, 10, 20, 20)
(1, 5, 10, 10, 10)
(1, 5, 10

(1, 1, 5, 5, 10)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 20)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 10)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 10, 20)
(1, 1, 5, 20, 20)
(1, 1, 5, 20, 20)
(1, 1, 5, 20, 20)
(1, 1, 5, 5, 5)
(1, 1, 5, 5, 5)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 5)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 20)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 10)
(1, 1, 5, 5, 20)
(1, 1,

(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 20, 20)
(5, 5, 5, 20, 20)
(5, 5, 5, 20, 20)
(5, 5, 5, 5, 10)
(5, 5, 5, 5, 10)
(5, 5, 5, 5, 10)
(5, 5, 5, 5, 10)
(5, 5, 5, 5, 10)
(5, 5, 5, 5, 20)
(5, 5, 5, 5, 20)
(5, 5, 5, 5, 20)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 10)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 10, 20)
(5, 5, 5, 20, 20)
(5, 5, 5, 20, 20)
(5, 5, 5, 20, 20)
(5, 5, 5, 10, 10)


**(b) Suppose you are going to purchase a 100-dollar merchant. How many ways can you make change for a $100 dollar bill? Use itertools methods to find the result. You may use loops for this question. (15 pts)**

In [22]:
oh_dollar =[]
for i in range(1,len(wallet)+1):
    for j in itertools.combinations(wallet,i):
        if sum(j) == 100:
            oh_dollar.append(j)
oh_dollar_way = len(set(oh_dollar))
ohh= len(oh_dollar)
print("Suppose no distinction in bills with same value: ",oh_dollar_way,"\notherwise :",ohh)

Suppose no distinction in bills with same value:  15 
otherwise : 1419


## Bonus (20 pts)

**1. Use a numpy function, create a evenly spaced number list over the range[-5, 5]. The list should contain 10 numbers.** <br>
Output: [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556, 0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ]

In [16]:
L = np.linspace(start =-5, stop=5,num=10)
L1=list(L)
print(L1)

[-5.0, -3.888888888888889, -2.7777777777777777, -1.6666666666666665, -0.5555555555555554, 0.5555555555555554, 1.666666666666667, 2.7777777777777786, 3.8888888888888893, 5.0]


**2. Use a numpy function to create a list full of 1s with length 5.** 

In [17]:
L = np.ones(5,dtype=int)
L1 = list(L)
print(L1)

[1, 1, 1, 1, 1]


**3. Use a numpy function to create two 3*2 matricies (named M and N) with randomly generated numbers. Doesn't have to be integers.** 

In [18]:
M = np.random.rand(3,2)
N = np.random.rand(3,2)
print("M is \n",M,"\n N is \n", N)

M is 
 [[0.49423684 0.84656149]
 [0.07964548 0.50524609]
 [0.0652865  0.42812233]] 
 N is 
 [[0.09653092 0.12715997]
 [0.59674531 0.226012  ]
 [0.10694568 0.22030621]]


**4. Use a numpy function, add N to the right of M to form a 3*4 matrix named K.** 

In [19]:
K = np.concatenate([M,N],axis =1)
print(K)

[[0.49423684 0.84656149 0.09653092 0.12715997]
 [0.07964548 0.50524609 0.59674531 0.226012  ]
 [0.0652865  0.42812233 0.10694568 0.22030621]]


**5. Use a numpy function, fill the matrix K with zeros. Suppose you do not know the dimension of K.** 

In [20]:
K1 = np.zeros_like(K,dtype=int)
print(K1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
